version: '3.8'

services:
  fighter-character:
    build:
      context: ..
      dockerfile: example-fighter/Dockerfile
      target: ${BUILD_TARGET:-production}
    container_name: character-${CHARACTER_NAME:-grax-fighter}
    restart: unless-stopped
    environment:
      # Character configuration
      - CHARACTER_ID=${CHARACTER_ID:-fighter-001}
      - CHARACTER_NAME=${CHARACTER_NAME:-Grax the Fighter}
      - CHARACTER_CLASS=fighter
      - CHARACTER_LEVEL=${CHARACTER_LEVEL:-3}
      - FIGHTING_STYLE=${FIGHTING_STYLE:-defense}
      
      # AI configuration
      - AI_AGGRESSIVENESS=${AI_AGGRESSIVENESS:-0.7}
      - AI_CAUTION=${AI_CAUTION:-0.4}
      - AI_CURIOSITY=${AI_CURIOSITY:-0.5}
      - AI_TACTICAL=${AI_TACTICAL:-0.8}
      
      # Game system connection
      - REGISTRY_URL=${REGISTRY_URL:-http://host.docker.internal:3001}
      - GAME_SERVER_URL=${GAME_SERVER_URL:-http://host.docker.internal:3000}
      - CHARACTER_ENDPOINT=http://character-${CHARACTER_NAME:-grax-fighter}:3000
      
      # Redis connection
      - REDIS_URL=${REDIS_URL:-redis://host.docker.internal:6379}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "${CHARACTER_PORT:-3001}:3000"
    volumes:
      # Persistent character data
      - fighter-data:/app/data
      - fighter-logs:/app/logs
      # Development hot reload (only in development)
      - ${PWD}/src:/app/src:${VOLUME_MOUNT_TYPE:-ro}
    networks:
      - dungeon-network
      - character-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { res.statusCode === 200 ? process.exit(0) : process.exit(1); }).on('error', () => process.exit(1));"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - fighter-redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Fighter-specific Redis for caching combat strategies
  fighter-redis:
    image: redis:7-alpine
    container_name: fighter-redis-${CHARACTER_NAME:-grax}
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispass123}
    ports:
      - "${CHARACTER_REDIS_PORT:-6381}:6379"
    volumes:
      - fighter-redis-data:/data
    networks:
      - character-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  fighter-data:
    driver: local
    name: fighter-data-${CHARACTER_NAME:-grax}
  fighter-logs:
    driver: local
    name: fighter-logs-${CHARACTER_NAME:-grax}
  fighter-redis-data:
    driver: local
    name: fighter-redis-data-${CHARACTER_NAME:-grax}

networks:
  dungeon-network:
    external: true
  character-network:
    driver: bridge
    name: character-network-${CHARACTER_NAME:-grax}